Panel_LogoXbox:SetShow(true, false)
local backGround = UI.getChildControl(Panel_LogoXbox, "Static_BackGround")
local button_Xbox = UI.getChildControl(Panel_LogoXbox, "Button_XboxPressA")
local txt_keyGuideA = UI.getChildControl(button_Xbox, "StaticText_A")
local txt_VersionInfo = UI.getChildControl(Panel_LogoXbox, "StaticText_VersionInfo")
local txt_betaWarning = UI.getChildControl(Panel_LogoXbox, "StaticText_BetaWarning")
txt_betaWarning:SetTextMode(CppEnums.TextMode.eTextMode_AutoWrap)
txt_betaWarning:SetText(txt_betaWarning:GetText())
function Panel_LogoXBox_Init()
  screenX = getScreenSizeX()
  screenY = getScreenSizeY()
  Panel_LogoXbox:SetSize(screenX, screenY)
  backGround:SetSize(screenX, screenY)
  backGround:SetShow(true)
  backGround:ComputePos()
  button_Xbox:SetShow(true)
  button_Xbox:ComputePos()
  txt_VersionInfo:SetShow(_ContentsGroup_ForXBoxClosedBeta)
  txt_VersionInfo:ComputePos()
  txt_betaWarning:ComputePos()
end
Panel_LogoXBox_Init()
function Panel_LogoXbox_PressA()
  _AudioPostEvent_SystemUiForXBOX(50, 8)
  ToClient_ActiveProcessXbox()
end
function Panel_LogoXbox_UpdatePerFrame(deltaTime)
end
Panel_LogoXbox:registerPadEvent(__eConsoleUIPadEvent_Up_A, "Panel_LogoXbox_PressA()")
button_Xbox:addInputEvent("Mouse_LUp", "Panel_LogoXbox_PressA()")
